language: java

jdk:
  - openjdk11

services:
  - docker

before_cache:
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/ $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
